"""Create an original, non-AI .remix fixture for offline playback checks."""

from __future__ import annotations

import argparse
import math
import struct
import tempfile
import wave
from pathlib import Path

from remixii.package import export_project, media_record
from remixii.schema import new_manifest

SAMPLE_RATE = 22050
DURATION = 10.0
NOTES = (220.0, 261.63, 293.66, 246.94)


def write_audio(path: Path, *, remix: bool) -> None:
    with wave.open(str(path), "wb") as audio:
        audio.setnchannels(1)
        audio.setsampwidth(2)
        audio.setframerate(SAMPLE_RATE)
        frames = bytearray()
        for sample in range(int(SAMPLE_RATE * DURATION)):
            t = sample / SAMPLE_RATE
            note = NOTES[int(t * 2) % len(NOTES)]
            melody = 0.20 * math.sin(2 * math.pi * note * t)
            if remix:
                beat_time = t % (60 / 128)
                kick = 0.44 * math.sin(2 * math.pi * 65 * beat_time) * math.exp(-beat_time * 22)
                value = melody * 0.75 + kick
            else:
                value = melody
            frames.extend(struct.pack("<h", int(max(-1, min(1, value)) * 32767)))
        audio.writeframes(frames)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("destination", type=Path)
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="remixii-offline-fixture-") as temporary:
        root = Path(temporary)
        source = root / "source.wav"
        mix = root / "mix.wav"
        write_audio(source, remix=False)
        write_audio(mix, remix=True)
        source_name = "media/source-excerpt.wav"
        mix_name = "media/selected-mix.wav"
        manifest = new_manifest(
            title="Offline playback test",
            creator="Remixii test generator",
            source_title="Original test melody",
            source_artist="Remixii test generator",
            source_recording="Programmatically generated test recording",
            influence="",
            permission_status="authorized",
            permission_evidence="Generated by this project for testing",
            excerpt_start=0,
            excerpt_end=DURATION,
            genre="Techno",
            bpm=128,
            vocal_treatment="instrumental",
            prompt="",
            model={
                "provider": "local non-AI test fixture",
                "model_name": "none",
                "model_revision": "none",
                "seed": None,
                "environment": "local",
                "parameters": {},
            },
            source_media=media_record(source, source_name, DURATION),
            mix_media=media_record(mix, mix_name, DURATION),
        )
        export_project(
            args.destination,
            manifest,
            {source_name: source, mix_name: mix},
        )


if __name__ == "__main__":
    main()
